# builder_deps
FROM node:14-alpine
ENV HTTP_PROXY="http://192.168.1.28:3128"
ENV HTTPS_PROXY="http://192.168.1.28:3128"
WORKDIR /app
RUN npm update -g
ENV NODE_ENV development
COPY ./package*.json ./
RUN npm ci
COPY . .
